spring.application.name=trainingspring
# MySQL 接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=43110misa6
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA設定（テーブルを自動的に更新）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
