spring.application.name=Thymeleaf_ren999  //課題の名前
 spring.datasource.url=jdbc:mysql://testdb　//どのツールのどのDBを使うよ　って宣言
 spring.datasource.username=root
 spring.datasource.password=43110misa6　//mysqlのパスワード
 spring.datasource.driver-class-name=com.mysql.cj.jdbc.driver